Editing data in tsv files for regeffect tables
ReddyLab/cegs-portal pull request #219
Opened 2023-11-06 18:41 UTC by UAMS16

The table data and the tsv data are not in sync. Edited the data to show the correct figures and headers from the table. Created another tsv_renderer for TargetEffectsView because the Regulatory Effects Table has its own specific data in it.
![image](https://github.com/ReddyLab/cegs-portal/assets/19657615/110ed63d-25ff-42dc-9b1a-c1fe4474ee5f)

2023-11-07 19:19 UTC, tncowart requested changes
Did you talk to Alex about the TSV formats?

2023-11-07 20:49 UTC, UAMS16 commented on cegs_portal/search/views/v1/reg_effects.py
> +from cegs_portal.search.tsv_templates.v1.reg_effects import (
Completed

2023-11-07 20:49 UTC, UAMS16 commented on cegs_portal/search/views/v1/reg_effects.py
> +
Completed

2023-11-07 20:49 UTC, UAMS16 commented on cegs_portal/search/templatetags/custom_helpers.py
> +@register.filter
completed

2023-11-07 20:50 UTC, UAMS16 commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +        source = reo.sources.all()[0]
Completed

2023-11-07 20:50 UTC, UAMS16 commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +        source = reo.sources.all()[0]
completed

2023-11-08 16:21 UTC, tncowart requested changes

2023-11-08 16:21 UTC, tncowart commented on cegs_portal/search/helpers/options.py
> +def is_bed6(options):
this doesn't need to be registered as a filter, and I think it could be used in non_targeting_reos.py

2023-11-08 20:16 UTC, tncowart requested changes

2023-11-08 20:16 UTC, tncowart commented on cegs_portal/search/views/v1/reg_effects.py
> +        if options is not None and options.get("tsv_format", None) == "bed6":
you can use `is_bed6` here

2023-11-08 20:16 UTC, tncowart commented on cegs_portal/search/views/v1/reg_effects.py
> +        if options is not None and options.get("tsv_format", None) == "bed6":
you can use `is_bed6` here.

2023-11-08 20:16 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +            tsv_data.append(row)
this needs to be indented one more unit to the left, so it's at the same level as `row = [`

2023-11-08 20:16 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +            for source in reo.sources.all():
If there are no targets this won't add anything to tsv_data.

2023-11-08 20:16 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +        for target in reo.targets.all():
If there are no targets this won't return any data.

2023-11-09 14:49 UTC, tncowart requested changes

2023-11-09 14:49 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +    return f"{source.chrom_name}:{source.location.lower}-{source.location.upper}:{if_strand(source.strand)}:{target.name if target else 'N/A'}"
The places where you call this function also tests if target is None (`tested_element(source, target) if target else "N/A"`). Which is correct - having the full name or having just "N/A"? My preference is for the full name, but with a small change:

```suggestion
    return f"{source.chrom_name}:{source.location.lower}-{source.location.upper}:{if_strand(source.strand)}{f':{target.name}' if target else ''}"
```

2023-11-09 14:49 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +        if not targets:
👍

2023-11-09 14:49 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +        if not targets:
👍

2023-11-09 18:06 UTC, tncowart commented on cegs_portal/search/tsv_templates/v1/reg_effects.py
> +    return f"{source.chrom_name}:{source.location.lower}-{source.location.upper}:{if_strand(source.strand)}:{target.name if target else 'N/A'}"
per Alex, leave the colon.

2023-11-09 18:08 UTC, tncowart approved these changes

2023-11-09 18:09 UTC, merged