Adding modal to experiment page. This allows the user to view experim…
ReddyLab/cegs-portal pull request #298
Opened 2024-06-03 18:21 UTC by UAMS16

…ent index without having to leave the page

2024-06-07 15:10 UTC, tncowart requested changes

2024-06-07 15:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/experiment.html
> +{% load waffle_tags %}
You aren't using a flag here, you don't need to load waffle_tags.

2024-06-07 15:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_experiment_index.html
> +</script>
Do you need this here or in experiment.html? I feel like it should be only in one place.

2024-06-07 15:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_experiment_index.html
> +</script>
I don't think you need the drag and drop set up for the modal.

2024-06-07 15:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_experiment_index.html
> +{% endif %}
I don't think users should be able to download stuff from the modal. I think this means you don't need to pass "logged_in" to the template from the view.

2024-06-07 15:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_experiment_index.html
> +{% block content %}
This is a template, so it doesn't extend base.html and thus, doesn't have a content or inline_javascript block.

2024-06-07 15:22 UTC, UAMS16 commented on cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
> -<div class="modal-underlay" onclick="closeModal()"></div>
This change was an accidental deletion being undone. This file shouldn't have been changed at all.

2024-06-11 16:19 UTC, tncowart requested changes

2024-06-11 16:19 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects.html
> -<div class="modal-underlay" onclick="closeModal()"></div>
This still hasn't been resolved.

2024-06-14 17:02 UTC, tncowart approved these changes

2024-06-14 18:04 UTC, merged