responsive search results page
ReddyLab/cegs-portal pull request #343
Opened 2024-08-13 15:58 UTC by UAMS16

2024-09-10 14:24 UTC, tncowart commented
Why are there a bunch of changes to experiment.html in this PR?

2024-09-10 14:58 UTC, tncowart requested changes

2024-09-10 17:10 UTC, UAMS16 commented
The "download" section, including buttons looks different here than all the other download sections. Also the text in this table looks smaller than the text in the other tables. Is that on purpose? 

Yes, we changed this table a few months ago. The DNA features table did not fit on the search results page(larger screen), so we had to adjust it(text, header, padding, margin, buttons etc) to fit within the allotted space. While the other tables span the full width of the page, this table’s space is limited by the filtering options on the right.

2024-09-12 12:59 UTC, tncowart approved these changes
Looks good!

2024-09-12 13:32 UTC, merged