Pagination added to Source for Regulatory effects to decrease load ti…
ReddyLab/cegs-portal pull request #39
Opened 2022-11-08 19:01 UTC by UAMS16

…me and  Created SRE html  page to display table.

2022-11-09 21:11 UTC, tncowart requested changes
This is looking great! I've left a few comments on the code. 

Additionally, this PR should include tests. the json template should have some tests -- you can probably mostly copy `json_templates/v1/tests/test_reg_effect.py` for that. You should also include an "endpoint" test, to make sure the endpoint is working for both HTML and JSON requests. See `views/v1/tests/test_dna_features.py` and `views/v1/tests/test_experiment.py` for an idea of what these look like.

2022-11-28 21:44 UTC, UAMS16 commented on cegs_portal/search/views/v1/reg_effects.py
> +        options["per_page"] = int(request.GET.get("per_page", 20))
Replaced Line 67 with reg_effect_paginator = Paginator(reg_effects, options["per_page"])

2022-11-28 21:57 UTC, UAMS16 commented on cegs_portal/search/views/v1/reg_effects.py
> +
1.	Empty line removed
2.	Deleted source_reg_effects in
cegs_portal.search.json_templates.v1.reg_effect
3.	Now using source_reg_effects in 
cegs_portal.search.json_templates.v1.source_reg_effects

2022-11-30 15:24 UTC, tncowart requested changes

2022-11-30 15:24 UTC, tncowart commented on cegs_portal/search/view_models/v1/reg_effects.py
> +                "experiment",
👍

2022-11-30 15:24 UTC, tncowart commented on cegs_portal/search/views/v1/reg_effects.py
> +from cegs_portal.search.json_templates.v1.source_reg_effects import (
I think that `source_reg_effects` should come from `cegs_portal.search.json_templates.v1.source_reg_effects` but that `regulatory_effect` should come from `cegs_portal.search.json_templates.v1.reg_effect`

2022-11-30 15:32 UTC, UAMS16 commented on cegs_portal/search/conftest.py
> +    return pages.page(1)
I think you changed it that Friday we went over tests. I have not worked with Experiment Tests.

2022-11-30 15:42 UTC, tncowart commented on cegs_portal/search/conftest.py
> +    return pages.page(1)
Ah, funny. I don't remember that at all!

2022-11-30 15:47 UTC, UAMS16 commented on cegs_portal/search/conftest.py
> +    return pages.page(1)
Ha! Yes, you were going pretty fast editing code etc. You usually just quickly fix or change things along the way while we go though code. Its like picking up trash along the road--nobody remembers when they do it.

2022-12-05 19:26 UTC, merged