Adding Glossary to navbar
ReddyLab/cegs-portal pull request #440
Opened 2024-11-14 19:31 UTC by UAMS16

![image](https://github.com/user-attachments/assets/d2dac9d6-0369-4ab7-b4e0-c614de436aa9)

2024-11-15 15:42 UTC, tncowart commented
Also, I don't think it's visually obvious that the footnote links (like "[26]") are links. Can you make it clearer? In my head I'm imagining the code would look something like `[<a href="#ref26">26</a>]` and visually link part would be "portal link"-colored and the brackets are text-colored.

2024-11-15 15:51 UTC, UAMS16 commented
Flowbite is for the modal functionality. Yes, I can make the link a portal link color.

2024-11-15 15:53 UTC, tncowart commented
We already use modals elsewhere in the application. Is there a reason you didn't use the same system here?

2024-11-15 16:09 UTC, UAMS16 commented
Yes, because its just for simple text, responsive design already built in, uses tailwind, already structured, quick and easy to use and not complicated. We've had to make many changes to our modals.

2024-11-22 20:39 UTC, tncowart requested changes

2024-11-22 20:39 UTC, tncowart commented on cegs_portal/search/urls.py
> +    path("glossary-partial/", views.glossary_partial, name="glossary_partial"),
Why glossary-partial and not just glossary?

2024-11-22 20:39 UTC, tncowart commented on cegs_portal/templates/base.html
> +    }
Indent one level

2024-11-22 20:39 UTC, tncowart commented on cegs_portal/templates/base.html
> +    }
Since these are now defined in base.html, can you take them out of the other pages that use them?

2024-11-22 20:39 UTC, tncowart commented on cegs_portal/templates/base.html
> +    }
Since this is now defined in base.html, can you take it out of the other pages that use is?

2024-12-02 19:00 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    Transcript: A messenger RNA (mRNA) molecule that carries genetic information from DNA to the cytoplasm, where proteins are made.[<a href="#ref24" class="link">24</a>]
```suggestion
                    Transcript: The <a class="link" href="https://www.britannica.com/science/messenger-RNA">messenger RNA (mRNA)</a> molecule created via gene transcripts is called a transcript. A single gene can have multiple transcripts.[<a href="#ref24" class="link">24</a>]
```

2024-12-02 19:08 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                </p>
Maybe have an entry for "accession id" here too, explaining our accession id system?

2024-12-02 19:13 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    H3K4me3: When combined, DNase-H3K4me3 elements are regions that exhibit both DNase hypersensitivity and H3K4me3 marks. These regions typically have promoter-like biochemical signa
```suggestion
                    H3K4me3: An epigenetic modification to one of the histones that makes up the non-DNA portion of a chromatin structure.[<a href="#ref28" class="link">28</a>]
```

2024-12-02 19:31 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    </ul>
```suggestion
                    <li id="ref32">32. <a href="https://screen.wenglab.org">https://screen.wenglab.org ("About")</a></li>
                     </ul>
```

2024-12-03 16:10 UTC, tncowart requested changes
A few more edits. I would also copy these definitions back to the google doc and ask for someone else to take a look at them.

2024-12-03 16:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    wgCERES: whole-genome CERES (wgCERES) a computational method to estimate gene dependency levels from CRISPR-Cas9 essentiality screens while accounting for the copy-number-specific
```suggestion
                    whole-genome CERES (wgCERES):  a computational method to estimate gene dependency levels from CRISPR-Cas9 essentiality screens while accounting for the copy-number-specific effect.[<a href="#ref5" class="link">5</a>]
```

2024-12-03 16:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    scCERES: single-cell (CERES) a computational method to estimate gene dependency levels from CRISPR-Cas9 essentiality screens while accounting for the copy-number-specific effect.[
```suggestion
                    single-cell CERES (scCERES): a computational method to estimate gene dependency levels from CRISPR-Cas9 essentiality screens while accounting for the copy-number-specific effect.[<a href="#ref5" class="link">5</a>]
```

2024-12-03 16:10 UTC, tncowart commented on cegs_portal/search/templates/search/v1/partials/_glossary.html
> +                    Accession ID: An identifier used by the Duke CCGR Portal to label experiments and their analyses. The format of the accession ID is DCPYYYYXXXXXXXXXX. The abbreviations DCP, EXPR,
```suggestion
                    Accession ID: An identifier used by the Duke CCGR Portal to label experiments and their analyses. The format of the accession ID is DCPYYYYXXXXXXXXXX. where the abbreviation DCP stands for ‘Duke CCGR Portal’. The "YYYY" section is used to indicate the type of item being accessioned and is not necessarily four characters long. For example, "EXPR" is used for experiments and "AN" is used for analyses. The Xs are the unique (within that type) number for the item and are a hexadecimal digits (0-F). Example: DCPEXPR0000000002 is Experiment 2.
```

2024-12-03 18:10 UTC, tncowart approved these changes

2024-12-03 18:11 UTC, merged